apiVersion: v1 
kind: Pod 
metadata: 
  name: azurefile-pod
spec:
  containers:
    - name: pod1
      image: nginx:1.28
      ports:
        - containerPort: 80
      volumeMounts: 
        - name: azurefile-volume
          mountPath: /fazurefileshare

  volumes: 
    - name: azurefile-volume
      azureFile: 
         secretName: azure-secret
         shareName: azurefile1
